feat: Improve UI with icon updates and font change
OpenBeta/open-tacos pull request #1084
Opened 2024-01-23 03:59 UTC by athuv

## What type of PR is this?(check all applicable)
- [ ] bug fix
- [ ] optimization

## Description

### Related Issues

Issue #1079

### What this PR achieves

1. Corrected the map and share buttons icons.
2. Changed the font to Inter.
3. Implemented Nextjs font optimization (next/font).

### Screenshots, recordings
![openbeta io_2](https://github.com/OpenBeta/open-tacos/assets/21102277/59c03b49-54f4-4380-b151-5f497673e8c7)

2024-01-25 17:29 UTC, musoke requested changes
Thank you for the PR!
I think your changes around the map and copy link buttons will be uncontroversial if you make the change I requested above.

Changing the font will likely need more discussion. In the interest of incorporating the icon changes faster, I suggest that you remove the font changes from this PR and submit them separately.

2024-01-25 17:29 UTC, musoke commented on src/app/components/ShareAreaLinkButton.tsx
> +        <ShareNetwork  size={20} /><span className='hidden md:inline'>Share</span>
As discussed in #1079, I suggest leaving the icon as is and changing the text from "Share" to "Copy Link"

2024-01-25 18:16 UTC, vnugent commented
@athuv can you fix linting errors and rebase? 
We use ts-standard which uses eslint under the hood.  You can install a VSC plugin:
https://marketplace.visualstudio.com/items?itemName=standard.vscode-standard

2024-01-25 18:20 UTC, vnugent requested changes

2024-01-25 18:20 UTC, vnugent commented on src/app/layout.tsx
> +      <body className={ inter.className}>
As discussed we will deal with font change in a separate task. In summary can you limit the PR to the following:
1. Update Map icon
2. Change share link label (not icon)

Thanks!

2024-01-31 10:37 UTC, athuv commented
@vnugent @musoke 

I would like to apologize for the inconvenience caused by my recent changes. I understand that the font and icon changes were not aligned with the project's requirements. I have now reverted the changes as per your instructions. I appreciate your patience and understanding in this matter. I assure you that I will pay closer attention to the project guidelines in the future.

Thank you for your time and consideration.

2024-01-31 17:49 UTC, vnugent commented
@athuv can you rebase, resolve conflicts and force push?  we're good to merge then.  Thanks!

2024-02-01 09:51 UTC, athuv commented
@vnugent 
- [x] Rebase
- [x] Resolve conflicts 
- [x] force push

2024-02-05 17:40 UTC, vnugent commented
@athuv can you redo the rebase?  Your recent commit included a lot of unwanted changes.  Since your PR is very small, it may be simpler to abandon the current working branch and repeat the work in a new PR.

2024-02-11 09:50 UTC, closed without merging