feat: enable user to share a link to the map that will open a drawer at a specific area id
OpenBeta/open-tacos pull request #1210
Opened 2024-11-11 01:38 UTC by clintonlunn

---
name: Pull request
about: Create a pull request
title: ''
labels: ''
assignees: ''

---

## What type of PR is this?(check all applicable)
- [ ] refactor
- [ ] feature
- [ ] bug fix
- [ ] documentation
- [ ] optimization
- [ ] other

## Description

### Related Issues

Issue #1209 

### What this PR achieves

### Screenshots, recordings

### Notes

2024-11-18 16:36 UTC, clintonlunn commented
@vnugent i think this PR is about complete. I made sure I am up to date with develop. This required some refactoring of existing camera params, which i've combined into a single useUrlParams in order to deal with the url in a single place. In addition, I've removed the debouncing that was happening for the camera movement, and instead change the url `onMoveEnd`, which I think gives us more expected behavior.

2024-11-22 17:19 UTC, vnugent requested changes
I made some inline comments.  It's great that you refactor the hooks to its own file. Not high priority (if you can do it in follow up PR) is to clear `areaId` when the user clicks elsewhere on the map (currently we close the drawer, clearing the current selected area). I think this behavior is consistent with other popular maps.

2024-11-22 17:19 UTC, vnugent commented on src/components/ui/ShareButton.tsx
Can we reuse the Share Link button on the climb/area page?

https://github.com/OpenBeta/open-tacos/blob/develop/src/app/(default)/components/AreaAndClimbPageActions.tsx#L39

2024-11-22 17:19 UTC, vnugent commented on src/app/(maps)/components/FullScreenMap.tsx
> +    if (urlAreaId !== null) {
We typically use `UrlAreaId != null` (single equal sign) to test for nullness and undefined

2024-11-22 17:19 UTC, vnugent commented on src/js/hooks/useUrlParams.tsx
> +    if (areaId !== null && areaId !== undefined) {
more concise `if (areaId != null)`

2024-11-27 22:01 UTC, vnugent requested changes

2024-11-27 22:01 UTC, vnugent commented on src/components/maps/GlobalMap.tsx
> +    if (feature === null || mapInstance === null) return
Can you change triple `===` to double catch both null and undefined?  (there are several instances).  Other than that I'm good to merge.

2024-12-04 00:26 UTC, merged