#68 Docker Container
OpenBeta/open-tacos pull request #127
Opened 2021-12-16 12:40 UTC by gibboj

Added docker for easier development setup

2021-12-16 18:47 UTC, vnugent commented
Thanks so much for the PR!   
I didn't mention anywhere in the README that `develop` is the default branch where we start our work from.  My apologies.  Would you be able to resubmit a new PR starting from `develop` branch?

You can cherry pick commit `88ca5f3` to the new branch.  For example:
```
git checkout develop
git checkout -b docker-container2
git cherry-pick 88ca5f3
```

2021-12-16 22:41 UTC, gibboj commented
@vnugent I rebased on develop. Let me know what you think

2021-12-17 07:49 UTC, vnugent commented
@allcontributors please add @gibboj as a contributor for code

2021-12-17 07:55 UTC, vnugent requested changes
@gibboj can you please make the 3 changes and push again? then we're ready to merge. Thanks!

2021-12-17 07:55 UTC, vnugent commented on docker-compose.yml
> +      - ./src:/myapp/src # Links the source files to the running container
I'd also map `node_modules` to the host to keep our docker image small
```
    volumes:
      - ./src:/myapp/src # Links the source files to the running container
      - ./node_modules:/myapp/node_modules
```

2021-12-17 07:55 UTC, vnugent commented on Dockerfile
> +RUN yarn global add gatsby-cli
we can access `gatsby-cli` which is already installed in `node_modules/.bin`

```

FROM node:16-bullseye-slim as builder

ENV GATSBY_TELEMETRY_DISABLED=1
ENV PATH /myapp/node_modules/.bin:$PATH

RUN apt-get update -y
# The port gatsby runs on
EXPOSE 8000
WORKDIR /myapp
COPY ./package.json /myapp
COPY ./yarn.lock /myapp
COPY . /myapp
CMD ["sh", "-c", "yarn install && gatsby develop -H 0.0.0.0"]

```

2021-12-17 07:55 UTC, vnugent commented on .dockerignore
> +public/
can you please add `opentacos-content`

2021-12-17 10:57 UTC, merged