added fix for issue Footer in user profile page not at bottom of screen when user has less photos. #462
OpenBeta/open-tacos pull request #463
Opened 2022-08-01 13:42 UTC by xavier-kong

Tested when user has more photos than page can fit without scrolling and when user has few photos.
![image](https://user-images.githubusercontent.com/86543341/182161079-1837a7a7-c37c-4a91-89b0-5d9277b16a7d.png)

2022-08-01 13:50 UTC, vnugent commented
`h-screen` paints the white background only to the end of the screen.  When you scroll down, the rest is in black.

See https://open-tacos-c4rmdmvwz-openbeta-dev.vercel.app/?v=newTags

<img width="986" alt="Screen Shot 2022-08-01 at 3 46 02 PM" src="https://user-images.githubusercontent.com/3805254/182162483-5d86c22c-c3a8-48c2-aa18-b46be91ba728.png">

2022-08-01 13:52 UTC, xavier-kong commented
I am using hard override dark mode on my machine so I did not catch that!

2022-08-01 18:21 UTC, vnugent requested changes

2022-08-01 18:21 UTC, vnugent commented on src/components/layout.tsx
> +  rootContainerClass = 'root-container-default flex flex-col',
how about add `flex flex-col` to `root-container-default` class in 
https://github.com/OpenBeta/open-tacos/blob/user-page-footer/src/styles/defaults.css#L16

2022-09-18 12:02 UTC, vnugent commented
@xavier-kong can you have a look at this?

2023-02-02 11:23 UTC, closed without merging