Add Scott's information to openbeta-devs file
OpenBeta/open-tacos pull request #957
Opened 2023-08-04 18:48 UTC by scooterh4

---
name: Pull request
about: Create a pull request
title: Add Scott's information to openbeta-devs file
labels: 
assignees: @actuallyyun 

---

## What type of PR is this?(check all applicable)
- [ ] refactor
- [ ] feature
- [ ] bug fix
- [X] documentation
- [ ] optimization
- [X] other

## Description

I added my information to the contributors-map.geojson file by following the tutorial on OpenBeta's website (https://docs.openbeta.io/how-to-contribute/dev-onboarding). I'm hoping for this to be the first PR of many. 

### Related Issues

Issue #

### What this PR achieves

This PR adds my information to the contributors-map.geojson file. I'd like this PR to act as an introduction to the OpenBeta project.

### Screenshots, recordings

### Notes

Let me know if there's anything I could've done different in documenting this PR. I have about ~1.5 years of developer experience so I am still fairly new to the field. I still have lots to learn and am keen to.

2023-08-05 00:35 UTC, vnugent requested changes

2023-08-05 00:35 UTC, vnugent commented on src/assets/contributors-map.geojson
> +          -115.1566
I think the coordinates need to be flip, ie `[-115.1566,  51.047]`

You can paste the entire file in  https://geojson.io/#map=11.01/51.0278/-115.1289 to verify the geojson format.
If the format is correct you will see a globe with drop pins.

2023-08-09 00:38 UTC, scooterh4 commented
Sorry about taking so long to fix this, I was away the last couple days. I think my most recent commit should fix the issue. I verified the location on the geojson website you provided.

2023-08-09 00:42 UTC, vnugent approved these changes

2023-08-09 00:42 UTC, merged